server:
  port: 8084

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_transaction_db
    username: postgres
    password: edsols
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        max.block.ms: 2000
        request.timeout.ms: 2000

jwt:
  secret: bXlTdXBlclNlY3VyZUJhbmtpbmdBcHBsaWNhdGlvblNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjIwMjQ=

services:
  account-service:
    url: http://localhost:8083

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.banking.transaction: DEBUG
    org.apache.kafka: WARN
